<?php $collection = $this->getHelloCollection(); ?>

<div id="map" style="height:500px"></div>

<script>
    var locations = [
        <?php foreach ($collection as $item): ?>  
            [
                "<?php echo $item->getName(); ?>", 
                <?php echo $item->getLat(); ?>, 
                <?php echo $item->getLong(); ?>, 
                "<?php echo $item->getAddress(); ?>",
                <?php echo $item->getId(); ?>,
            ],
        <?php endforeach; ?>
    ];

    function initMap() {
        var myOptions = {
            center: new google.maps.LatLng(48.863184, 2.331544),
            zoom: 8,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map"), myOptions);
        
        setMarkers(map,locations);
    }

    function setMarkers(map,locations){
        var marker, i;
        var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

        for (i = 0; i < locations.length; i++){  

            var loan = locations[i][0];
            var lat = locations[i][1];
            var long = locations[i][2];
            var add =  locations[i][3];
            var id =  locations[i][4];

            var url = "http://localhost/Magento-CE-2.2.3-2018-02-22-04-51-53/storelocator/stores/infos/" + id;

            latlngset = new google.maps.LatLng(lat, long);

            var marker = new google.maps.Marker({  
                map: map,
                label: labels[i % labels.length], 
                title: loan , 
                position: latlngset  
            });
            map.setCenter(marker.getPosition());
            var content =   "<h3>" + loan + '</h3>' + 
                            "<small>" + add + "</small>" +
                            "<p><a href ='" + url + "'>Details</a></p>";
            var infowindow = new google.maps.InfoWindow();

            google.maps.event.addListener(marker,'click', (function(marker,content,infowindow){ 
                return function() {
                    infowindow.setContent(content);
                    infowindow.open(map,marker);
                };
            })(marker,content,infowindow)); 
        }
    }
</script>
<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAqp3YHHox5uGXGwiQkK4uyuW5ws5gFdSM&callback=initMap"></script>