<?php
$collection = $this->getHelloCollection();
?>

<div id="storelocatorlist">
    <h2>empty</h2>
    <table>
        <tr>
            <th>Name</th>
        </tr>
        <?php $contacts = $this->getData('storelocator'); ?>
        <?php foreach ($contacts as $contact): ?>
            <tr>
                <td><?php echo $contact ?></td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td>there is no contact in this list</td>
        </tr>
    </table>

    <h2>10 éléments</h2>
    <table>
        <tr>
            <th>Name</th>
        </tr>
        <?php $this->addStorelocator(10); ?>
        <?php $contacts = $this->getData('storelocator'); ?>
        <?php foreach ($contacts as $contact): ?>
            <tr>
                <td><?php echo $contact ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<div id="map" style="height:500px"></div>
<script>
    var locations = [
        <?php foreach ($collection as $item): ?>  
            {lat: <?php echo $item->getLat(); ?>, lng: <?php echo $item->getLong(); ?>},
        <?php endforeach; ?>
        {lat: -37.819616, lng: 144.968119},
        {lat: -38.330766, lng: 144.695692},
    ];

    function initMap() {

        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 3,
            center: {lat: -28.024, lng: 140.887}
        });

        // Create an array of alphabetical characters used to label the markers.
        var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

        // Add some markers to the map.
        // Note: The code uses the JavaScript Array.prototype.map() method to
        // create an array of markers based on a given "locations" array.
        // The map() method here has nothing to do with the Google Maps API.
        var markers = locations.map(function(location, i) {
        return new google.maps.Marker({
                position: location,
                label: labels[i % labels.length]
            });
        });

        // Add a marker clusterer to manage the markers.
        var markerCluster = new MarkerClusterer(map, markers,
            {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'}
        );
    }
</script>
<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAqp3YHHox5uGXGwiQkK4uyuW5ws5gFdSM&callback=initMap"></script>